[book]
authors = ["John Telford"]
language = "en"
src = "src"
title = "Interative Web Development"

[preprocessor]

[preprocessor.admonish]
command = "mdbook-admonish"

[preprocessor.image-size]
command = "mdbook-image-size"
